kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
#  apiServerAddress: "192.168.56.1"
  apiServerAddress: "10.76.2.148"
  apiServerPort: 58350
#   disableDefaultCNI: false
# nodes:
#   - role: control-plane
#     extraPortMappings:
#         - containerPort: 80
#           hostPort: 80
#           protocol: TCP
#         - containerPort: 443
#           hostPort: 443
#           protocol: TCP
#         - containerPort: 30000
#           hostPort: 30000
#           protocol: TCP # for the dashboard
#         - containerPort: 30080
#           hostPort: 30080
#           protocol: TCP # for gogs
#         - containerPort: 30022
#           hostPort: 30022
#           protocol: TCP # for gogs